//go:build ignore

// Generates the compressible extension lists for Go, JS/TS, and Rust
// from jshttp/mime-db.
//
// Usage:
//
//	go run scripts/gen.go
//
// Output files (overwritten in place):
//
//	go/extensions.go
//	js/src/extensions.ts
//	rust/src/extensions.rs
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const mimeDBURL = "https://cdn.jsdelivr.net/gh/jshttp/mime-db@master/db.json"

// MIME types to exclude even if mime-db marks them compressible
// (these typically wrap already-compressed or archive content, or are
// large binary blobs that are not useful to gzip).
var excludeMIMETypes = map[string]bool{
	"application/octet-stream": true,
	"application/x-tar":        true,
	// VM disk images / archives: huge binaries, often sparse or
	// internally compressed; .ova is itself a tar archive.
	"application/x-virtualbox-hdd":  true,
	"application/x-virtualbox-vdi":  true,
	"application/x-virtualbox-vhd":  true,
	"application/x-virtualbox-vmdk": true,
	"application/x-virtualbox-ova":  true,
	// Already-compressed image / texture formats.
	"image/vnd.ms-dds":          true, // DXT/BCn compressed texture
	"image/vnd.adobe.photoshop": true, // PSD has internal RLE/ZIP
}

// Extensions to exclude regardless of MIME type
// (some MIME types map to both compressed and uncompressed extensions).
var excludeExts = map[string]bool{
	"svgz": true, // pre-gzipped SVG
	"x3dz": true, // pre-gzipped X3D
}

// Extra extensions to always include (not all are covered by mime-db).
var extraExts = []string{
	"bin",
	// 3D Tiles
	"b3dm",
	"i3dm",
	"pnts",
	"cmpt",
	"subtree",
	// Cesium quantized-mesh terrain
	"terrain",
}

type entry struct {
	Compressible bool     `json:"compressible"`
	Extensions   []string `json:"extensions"`
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	body, err := fetch()
	if err != nil {
		return err
	}

	var db map[string]entry
	if err := json.Unmarshal(body, &db); err != nil {
		return fmt.Errorf("parse mime-db: %w", err)
	}

	set := map[string]struct{}{}
	for mt, e := range db {
		if !e.Compressible || len(e.Extensions) == 0 {
			continue
		}
		if excludeMIMETypes[mt] {
			continue
		}
		for _, ext := range e.Extensions {
			ext = strings.ToLower(ext)
			if excludeExts[ext] {
				continue
			}
			set[ext] = struct{}{}
		}
	}
	for _, ext := range extraExts {
		set[strings.ToLower(ext)] = struct{}{}
	}

	exts := make([]string, 0, len(set))
	for ext := range set {
		exts = append(exts, ext)
	}
	sort.Strings(exts)

	root, err := repoRoot()
	if err != nil {
		return err
	}

	if err := writeGo(filepath.Join(root, "go", "extensions.go"), exts); err != nil {
		return fmt.Errorf("write go: %w", err)
	}
	if err := writeTS(filepath.Join(root, "js", "src", "extensions.ts"), exts); err != nil {
		return fmt.Errorf("write ts: %w", err)
	}
	if err := writeRust(filepath.Join(root, "rust", "src", "extensions.rs"), exts); err != nil {
		return fmt.Errorf("write rust: %w", err)
	}

	log.Printf("wrote %d extensions to go/, js/, rust/", len(exts))
	return nil
}

func fetch() ([]byte, error) {
	// Allow offline use via a local file fallback (useful in tests / CI cache).
	if p := os.Getenv("MIME_DB_FILE"); p != "" {
		return os.ReadFile(p)
	}
	resp, err := http.Get(mimeDBURL)
	if err != nil {
		return nil, fmt.Errorf("fetch mime-db: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetch mime-db: status %d", resp.StatusCode)
	}
	return io.ReadAll(resp.Body)
}

// repoRoot returns the directory containing the scripts/ directory this file
// lives in, i.e. the repository root.
func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	// If invoked as `go run scripts/gen.go` from the repo root, wd is repo root.
	if _, err := os.Stat(filepath.Join(wd, "scripts", "gen.go")); err == nil {
		return wd, nil
	}
	// If invoked from inside scripts/, walk up one.
	if _, err := os.Stat(filepath.Join(wd, "gen.go")); err == nil {
		return filepath.Dir(wd), nil
	}
	return "", fmt.Errorf("cannot find repo root from %s", wd)
}

const header = "// Code generated by scripts/gen.go; DO NOT EDIT.\n" +
	"// Source: https://github.com/jshttp/mime-db\n"

func writeGo(path string, exts []string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("\npackage compressible\n\n")
	buf.WriteString("// exts is the set of file extensions (without leading dot,\n")
	buf.WriteString("// lowercased) whose contents benefit from gzip compression.\n")
	buf.WriteString("var exts = map[string]struct{}{\n")
	for _, e := range exts {
		fmt.Fprintf(&buf, "\t%q: {},\n", e)
	}
	buf.WriteString("}\n")
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt: %w", err)
	}
	return os.WriteFile(path, src, 0644)
}

func writeTS(path string, exts []string) error {
	var buf bytes.Buffer
	buf.WriteString(strings.ReplaceAll(header, "//", "//"))
	buf.WriteString("\n")
	buf.WriteString("// Set of file extensions (without leading dot, lowercased) whose\n")
	buf.WriteString("// contents benefit from gzip compression.\n")
	buf.WriteString("export const extensions: ReadonlySet<string> = new Set([\n")
	for _, e := range exts {
		fmt.Fprintf(&buf, "  %q,\n", e)
	}
	buf.WriteString("]);\n")
	return os.WriteFile(path, buf.Bytes(), 0644)
}

func writeRust(path string, exts []string) error {
	var buf bytes.Buffer
	buf.WriteString(header)
	buf.WriteString("\n")
	buf.WriteString("// Sorted slice of file extensions (without leading dot, lowercased) whose\n")
	buf.WriteString("// contents benefit from gzip compression. Lookups use binary search.\n")
	fmt.Fprintf(&buf, "pub(crate) static EXTENSIONS: [&str; %d] = [\n", len(exts))
	for _, e := range exts {
		fmt.Fprintf(&buf, "    %q,\n", e)
	}
	buf.WriteString("];\n")
	return os.WriteFile(path, buf.Bytes(), 0644)
}
